const PERSONNEL_ROLES = ["FIELD_AGENT", "ANALYST", "RESEARCHER", "ADMIN"];
const ACCESS_LEVELS = [...PERSONNEL_ROLES];
const MISSION_STATUS = ["NOT_STARTED", "IN_PROGRESS", "COMPLETE"];
const MISSION_OUTCOMES = ["SUCCESS", "FAILURE", "PARTIAL_SUCCESS"];
const RISK_CLASSIFICATIONS = ["SAFE", "UNSTABLE", "DANGEROUS", "PARADOX"];
const CONTAINMENT_STATUS = ["CONTAINED", "UNDER_STUDY", "MISSING"];
const COLLECTIONS = {
  personnel: "Personnel",
  mission: "Mission",
  containment: "ContainmentUnit",
  relic: "Relic",
  accesslog: "AccessLog"
};

const ROLE_PRIORITY = {
  FIELD_AGENT: 1,
  ANALYST: 2,
  RESEARCHER: 3,
  ADMIN: 4
};

module.exports = {
  ACCESS_LEVELS,
  COLLECTIONS,
  CONTAINMENT_STATUS,
  MISSION_OUTCOMES,
  MISSION_STATUS,
  PERSONNEL_ROLES,
  RISK_CLASSIFICATIONS,
  ROLE_PRIORITY
};
